
const defaultsmells = [
  { id: 0, name: "Hindbær" },
  { id: 1, name: "Lime" },
  { id: 2, name: "Timian" },
  { id: 3, name: "Eddike" },
  { id: 4, name: "Karry" },
  { id: 5, name: "Karamel" },
  { id: 6, name: "Ananas" },
  { id: 7, name: "Pebermynte" },
  { id: 8, name: "Kamille" },
  { id: 9, name: "Kirsebær" },
  { id: 10, name: "Abrikos" },
  { id: 11, name: "Kardemomme" },
  { id: 12, name: "Allehånde" },
  { id: 13, name: "Koriander" },
  { id: 14, name: "Spidskommen" },
  { id: 15, name: "Kaffe" },
  { id: 16, name: "Kanel" },
  { id: 17, name: "Mandel" },
  { id: 18, name: "Vanilje" },
  { id: 19, name: "Nellike" },
  { id: 20, name: "Rosmarin" },
  { id: 21, name: "Muskat" },
  { id: 22, name: "Ingefær" },
  { id: 23, name: "Cayenne" },
  { id: 24, name: "Anis" },
  { id: 25, name: "Banan" },
  { id: 26, name: "Kokos" },
  { id: 27, name: "Peanuts" },
  { id: 28, name: "Mandarin" },
  { id: 29, name: "Jordbær" },
  { id: 30, name: "Estragon" },
  { id: 31, name: "Peber" }, ,
  { id: 32, name: "Basilikum" },
  { id: 33, name: "Enebær" },
  { id: 34, name: "Citron" },
  { id: 35, name: "Eucalyptus" },
  { id: 36, name: "Appelsin" },
  { id: 37, name: "Lavendel" },
  { id: 38, name: "Grape" },
  { id: 39, name: "Rose" },
  { id: 40, name: "Kamfer" },
  { id: 41, name: "Cedertræ" },
  { id: 42, name: "Gran" },
];


